version: "2.1"
services:
  flask:
    env_file:
      - core/.env
    container_name: chatgp_flask
    build: core/
    ports:
      - "127.0.0.1:5123:5000"
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./core:/core
    entrypoint: ["/app/init_app_dev.sh"]
  db:
    env_file:
      - core/.env
    container_name: chatgpt_pg
    image: postgres
    restart: always
    expose:
      - "5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  backend:
